[mqtt]
host = "localhost"
port = 1883
username = ""
password = ""

[[zones]]
name = "South Basement Workshop"

[zones.filter]
command_topic = "air-filter/south~basement/fan/cmd"

[[zones.air_quality]]
topic = "sensors/south-basement/sensor/particulate_matter_1_0/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.air_quality]]
topic = "sensors/south-basement/sensor/particulate_matter_2_5/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.air_quality]]
topic = "sensors/south-basement/sensor/particulate_matter_10_0/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.presence]]
topic = "sensors/south-basement/binary_sensor/motion_1/state"
timeout = 90

[[zones.presence]]
topic = "sensors/south-basement/binary_sensor/motion_2/state"
timeout = 90

[[zones]]
name = "North Basement Workshop"

[zones.filter]
command_topic = "air-filter/north~basement/fan/cmd"

[[zones.air_quality]]
topic = "sensors/north-basement/sensor/particulate_matter_1_0/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.air_quality]]
topic = "sensors/north-basement/sensor/particulate_matter_2_5/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.air_quality]]
topic = "sensors/north-basement/sensor/particulate_matter_10_0/state"
pre_dirty_threshold = 8
dirty_threshold = 15
very_dirty_threshold = 50

[[zones.presence]]
topic = "sensors/north-basement/binary_sensor/motion_1/state"
timeout = 90
