---
esphome:
  name: south-basement-air-sensor

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

wifi:
  ssid: Maker Space
  password: !secret wifi_password

mqtt:
  broker: 192.168.8.183
  username: airsensors
  password: !secret mqtt_password

  topic_prefix: sensors/south-basement
  discovery: false

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO16
      mode:
        input: true
        pulldown: true
    name: Motion 1
    device_class: motion

  - platform: gpio
    pin:
      number: GPIO17
      mode:
        input: true
        pulldown: true
    name: Motion 2
    device_class: motion

uart:
  - id: uart_1
    rx_pin: GPIO26
    tx_pin: GPIO27
    baud_rate: 9600

sensor:
  - platform: pmsx003
    uart_id: uart_1
    update_interval: 60s
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter 1.0"
    pm_2_5:
      name: "Particulate Matter 2.5"
    pm_10_0:
      name: "Particulate Matter 10.0"
