---
name: Control Program

on:
  push:
    branches:
      - main
    paths:
      - 'flake.*'
      - 'control/**'
  pull_request:
    paths:
      - 'flake.*'
      - 'control/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./control

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Clippy
        run: |
          eval "$(nix print-dev-env)"
          set -x

          cargo clippy -- -Dwarnings

      - name: Test
        run: |
          eval "$(nix print-dev-env)"
          set -x

          cargo test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    defaults:
      run:
        working-directory: ./control

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Build
        run: |
          eval "$(nix print-dev-env)"
          set -x

          cargo build --release
