---
name: Control Program

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/control.yml'
      - 'devenv.*'
      - 'control/**'
  pull_request:
    paths:
      - '.github/workflows/control.yml'
      - 'devenv.*'
      - 'control/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: |
          cd ./control
          cargo clippy -- -Dwarnings

      - name: Test
        shell: devenv shell bash -- -e {0}
        run: |
          cd ./control
          cargo test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          cd ./control
          cargo build --release
