---
name: Firmware

on:
  push:
    branches:
      - main
    paths:
      - 'flake.*'
      - 'firmware/**'
  pull_request:
    paths:
      - 'flake.*'
      - 'firmware/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./firmware

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Clippy
        env:
          WIFI_PASSWORD: super secret
          MQTT_PASSWORD: lol nope
          CONFIG: ./configs/test.toml
        run: |
          eval "$(nix print-dev-env)"
          set -x

          rustup target add thumbv6m-none-eabi
          rustup show

          cargo clippy -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    defaults:
      run:
        working-directory: ./firmware

    strategy:
      matrix:
        config:
          - north-basement-workshop.toml
          - south-basement-workshop.toml
          - test.toml

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30

      - name: Build
        env:
          WIFI_PASSWORD: super secret
          MQTT_PASSWORD: lol nope
          CONFIG: "./configs/${{ matrix.config }}"
        run: |
          eval "$(nix print-dev-env)"
          set -x

          rustup target add thumbv6m-none-eabi
          rustup show

          cargo build --release --no-default-features
