---
name: Firmware

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/firmware.yml'
      - 'devenv.*'
      - 'firmware/**'
  pull_request:
    paths:
      - '.github/workflows/firmware.yml'
      - 'devenv.*'
      - 'firmware/**'

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Clippy
        shell: devenv shell bash -- -e {0}
        run: |
          set -x

          cd ./firmware

          rustup target add thumbv6m-none-eabi
          rustup show

          cargo clippy -- -Dwarnings

  build:
    name: Build
    runs-on: ubuntu-latest
    needs:
      - quality

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build
        shell: devenv shell bash -- -e {0}
        run: |
          set -x

          cd ./firmware

          rustup target add thumbv6m-none-eabi
          rustup show

          cargo build --release
